# Generated by Django 5.2.6 on 2025-09-24 06:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_interest_rate_loanrule_max_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
