# Generated by Django 5.2.6 on 2025-09-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_bank_bank_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('min_tenure', models.IntegerField(blank=True, null=True)),
                ('max_tenure', models.IntegerField(blank=True, null=True)),
                ('min_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_roi', models.FloatField(blank=True, null=True)),
                ('max_roi', models.FloatField(blank=True, null=True)),
                ('foir_details', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bankapp.bank')),
            ],
        ),
    ]
