# Generated by Django 5.2.6 on 2025-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='state',
        ),
        migrations.AlterField(
            model_name='bank',
            name='pincode',
            field=models.CharField(blank=True, help_text='Enter multiple pincodes separated by commas, e.g., 110001,110002', max_length=500, null=True),
        ),
    ]
