# Generated by Django 5.2.6 on 2025-10-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_remove_bank_state_alter_bank_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
