# Generated by Django 5.2.6 on 2025-10-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCriteria',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_criteria', to='bankapp.companycategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_criteria', to='bankapp.product')),
            ],
        ),
    ]
