# Generated by Django 5.2.6 on 2025-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_salarycriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cat_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cat_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='government',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='partnership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='proprietorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='super_cat_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
