# Generated by Django 5.2.6 on 2025-10-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_product_cat_a_product_cat_b_product_cat_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_a',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_b',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_c',
        ),
        migrations.RemoveField(
            model_name='product',
            name='government',
        ),
        migrations.RemoveField(
            model_name='product',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proprietorship',
        ),
        migrations.RemoveField(
            model_name='product',
            name='super_cat_a',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unlisted',
        ),
    ]
