# Generated by Django 5.2.6 on 2025-10-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0014_customer_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanRule',
        ),
    ]
