# Generated by Django 5.2.6 on 2025-10-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0015_delete_loanrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinterest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_interests', to='bankapp.product'),
        ),
    ]
