# Generated by Django 5.2.6 on 2025-10-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0016_customerinterest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_eligibility_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
