# Generated by Django 5.2.6 on 2025-09-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrule',
            old_name='interest_rate',
            new_name='max_rate',
        ),
        migrations.AddField(
            model_name='loanrule',
            name='min_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrule',
            name='tenure',
            field=models.IntegerField(blank=True, help_text='Tenure in months or years', null=True),
        ),
    ]
